

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/skeleton
    username: root
    password: admin1234

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        globally_quoted_identifiers: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    project.backend: debug

server:
  port: 8080
  error:
    include-exception: true     # 응답에 exception의 내용을 포함할지 여부
    path: '/error'               # 응답을 처리할 Handler의 경로
    whitelabel:
      enabled: true             # 서버 오류 발생시 브라우저에 보여줄 기본 페이지 생성 여부